### ISSUE TITLE
Footer Component

### ISSUE THREAD

**Issue by SafeDuck** [acm-ucr/highlander-gloves-website#5]
![image](https://github.com/user-attachments/assets/2eaa9ada-1d86-4267-b1ad-910fc5b1abf7)

## Requirements: 
1. install react icons
2. Create json array in data folder containing text, link, and react-icon
3. Map through json array and render to DOM

Hint: Must use absolute positioning for the Logo behind the text

**Comment by ASANIYAN** [comment]
Hello. 
Can I be assigned this issue?
Can you also explain the part regarding the logo behind the text, what exactly do you want to achieve?
